<?php
declare(strict_types=1);
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/db.php';
require_once __DIR__ . '/functions.php';
function create_monitor_tables_if_needed(): void { ensure_core_schema(); db()->exec('CREATE TABLE IF NOT EXISTS monitor_check_log (id INTEGER PRIMARY KEY AUTOINCREMENT, website_id INTEGER, service_id INTEGER, result TEXT NOT NULL, http_code INTEGER, error_message TEXT, response_ms INTEGER, checked_url TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)'); }
function looks_like_cloudflare_down_page(string $body): bool { $n=['web server is down','host error','origin is unreachable','connection timed out','bad gateway','gateway timeout','error 521','error 522','error 523','error 524','error 525','error 526','cf-error-code']; $b=strtolower($body); foreach($n as $x) if(str_contains($b,$x)) return true; return false; }
function check_url_health(string $url, ?string $expectedText=null): array { $started=microtime(true); $url=normalize_url($url); $ch=curl_init($url); curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_MAXREDIRS=>4,CURLOPT_TIMEOUT=>MONITOR_HTTP_TIMEOUT_SECONDS,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_HEADER=>true,CURLOPT_USERAGENT=>'FareBrosStatusMonitor/1.0',CURLOPT_NOBODY=>false]); $raw=curl_exec($ch); $err=curl_error($ch); $code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE); $hs=(int)curl_getinfo($ch,CURLINFO_HEADER_SIZE); curl_close($ch); $ms=(int)round((microtime(true)-$started)*1000); if($raw===false||$err!=='') return ['online'=>false,'result'=>'offline','http_code'=>$code?:null,'error'=>$err?:'Request failed.','response_ms'=>$ms]; $body=substr((string)$raw,$hs); if($code>=500||$code===0) return ['online'=>false,'result'=>'offline','http_code'=>$code,'error'=>'HTTP '.$code,'response_ms'=>$ms]; if(looks_like_cloudflare_down_page($body)) return ['online'=>false,'result'=>'offline','http_code'=>$code,'error'=>'Cloudflare/origin error page detected.','response_ms'=>$ms]; if($code>=200&&$code<400) return ['online'=>true,'result'=>'online','http_code'=>$code,'error'=>null,'response_ms'=>$ms]; return ['online'=>false,'result'=>'offline','http_code'=>$code,'error'=>'Unexpected HTTP '.$code,'response_ms'=>$ms];}
function get_farebros_core_service_id(): ?int { $q=db()->prepare('SELECT id FROM services WHERE service_name=? LIMIT 1'); $q->execute(['Fare Brothers Core']); $r=$q->fetch(); return $r?(int)$r['id']:null; }
function apply_website_monitor_result(array $w,array $r): array { $wid=(int)$w['id']; $old=(string)$w['current_status']; $new=match($r['result']){'online'=>'operational','degraded'=>'degraded',default=>'offline'}; db()->prepare('UPDATE websites SET current_status=?,last_http_code=?,last_error=?,last_checked_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$new,$r['http_code'],$r['error'],$wid]); $sid=null; if((int)$w['is_primary']===1){$sid=get_farebros_core_service_id(); if($sid) db()->prepare('UPDATE services SET current_status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$new,$sid]);} db()->prepare('INSERT INTO monitor_check_log (website_id,service_id,result,http_code,error_message,response_ms,checked_url) VALUES (?,?,?,?,?,?,?)')->execute([$wid,$sid,$r['result'],$r['http_code'],$r['error'],$r['response_ms'],$w['website_url']]); if($old!==$new){$title=$w['website_name'].' is '.($new==='operational'?'online':($new==='degraded'?'degraded':'offline')); $msg=$new==='operational'?$w['website_name'].' is responding normally from the offsite monitor.':$w['website_name'].' is not responding normally from the offsite monitor. '.($r['error']??''); db()->prepare('INSERT INTO status_updates (service_id,old_status,new_status,update_title,update_message,created_by) VALUES (?,?,?,?,?,NULL)')->execute([$sid,$old,$new,$title,trim($msg)]);} return ['website_id'=>$wid,'website_name'=>$w['website_name'],'old_status'=>$old,'new_status'=>$new,'changed'=>$old!==$new,'result'=>$r]; }
function run_all_monitors(): array { create_monitor_tables_if_needed(); if(!MONITORING_ENABLED)return ['ok'=>false,'message'=>'Monitoring is disabled.','results'=>[]]; $out=[]; foreach(get_websites() as $w) $out[]=apply_website_monitor_result($w,check_url_health($w['website_url'],'')); return ['ok'=>true,'checked_at'=>date('c'),'results'=>$out]; }
function get_recent_monitor_logs(int $limit=25): array { create_monitor_tables_if_needed(); $q=db()->prepare('SELECT mcl.*,w.website_name,s.service_name FROM monitor_check_log mcl LEFT JOIN websites w ON w.id=mcl.website_id LEFT JOIN services s ON s.id=mcl.service_id ORDER BY mcl.created_at DESC LIMIT ?'); $q->bindValue(1,$limit,PDO::PARAM_INT); $q->execute(); return $q->fetchAll(); }
